# Generated by Django 6.0.6 on 2026-06-15 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetSauvegarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(max_length=255, verbose_name='Nom du projet')),
                ('db_name', models.CharField(max_length=255, verbose_name='Nom de la base de données')),
                ('db_user', models.CharField(max_length=255, verbose_name='Utilisateur DB')),
                ('db_password', models.CharField(max_length=255, verbose_name='Mot de passe DB')),
                ('db_host', models.CharField(default='localhost', max_length=255, verbose_name='Hôte DB')),
                ('db_port', models.CharField(default='5432', max_length=10, verbose_name='Port DB')),
                ('chemin_media_local', models.CharField(max_length=500, verbose_name='Chemin local des médias')),
                ('frequence_minutes', models.IntegerField(default=60, verbose_name='Fréquence (minutes)')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('lancer_au_demarrage', models.BooleanField(default=False, verbose_name='Lancer au démarrage')),
            ],
            options={
                'verbose_name': 'Projet de sauvegarde',
                'verbose_name_plural': 'Projets de sauvegarde',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueSauvegarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_execution', models.DateTimeField(auto_now_add=True, verbose_name="Date d'exécution")),
                ('type_action', models.CharField(choices=[('sauvegarde', 'Sauvegarde'), ('restauration', 'Restauration')], max_length=50, verbose_name="Type d'action")),
                ('statut', models.CharField(choices=[('succes', 'Succès'), ('echec', 'Échec')], max_length=50, verbose_name='Statut')),
                ('message_log', models.TextField(blank=True, verbose_name='Message de log')),
                ('chemin_archive_generee', models.CharField(blank=True, max_length=500, verbose_name="Chemin de l'archive générée")),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='module_sauvegarde.projetsauvegarde', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Historique de sauvegarde',
                'verbose_name_plural': 'Historiques de sauvegarde',
                'ordering': ['-date_execution'],
            },
        ),
        migrations.CreateModel(
            name='DestinationSauvegarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_destination', models.CharField(choices=[('local', 'Local'), ('gdrive', 'Google Drive'), ('onedrive', 'OneDrive')], max_length=50, verbose_name='Type de destination')),
                ('chemin_local', models.CharField(blank=True, max_length=500, null=True, verbose_name='Chemin local')),
                ('token_auth_cloud', models.TextField(blank=True, null=True, verbose_name='Token Auth Cloud')),
                ('dossier_cible_cloud', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dossier cible Cloud (ID/Chemin)')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='module_sauvegarde.projetsauvegarde', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Destination de sauvegarde',
                'verbose_name_plural': 'Destinations de sauvegarde',
            },
        ),
    ]
